export const mockCategories = [
  {
    _id: "cat-diy",
    name: { en: "DIY / Handmade", zh: "DIY / 手作类" },
    slug: { current: "diy-handmade" },
    description: {
      en: "Create beautiful handmade items with your own hands",
      zh: "用双手创造美好的手工作品",
    },
    icon: "palette",
    order: 1,
  },
  {
    _id: "cat-acc",
    name: { en: "Accessories", zh: "饰品/挂件类" },
    slug: { current: "accessories" },
    description: {
      en: "Stylish accessories and charms you can make yourself",
      zh: "可以自己制作的时尚饰品和挂件",
    },
    icon: "gem",
    order: 2,
  },
  {
    _id: "cat-toys",
    name: { en: "Toys & Blind Box", zh: "玩具/盲盒类" },
    slug: { current: "toys-blindbox" },
    description: {
      en: "Fun toys, blind boxes, and building sets",
      zh: "有趣的玩具、盲盒和拼装模型",
    },
    icon: "box",
    order: 3,
  },
  {
    _id: "cat-events",
    name: { en: "Events & Parties", zh: "活动/派对类" },
    slug: { current: "events-parties" },
    description: {
      en: "Special events and party experiences",
      zh: "特别活动和派对体验",
    },
    icon: "party-popper",
    order: 4,
  },
  {
    _id: "cat-others",
    name: { en: "Others", zh: "其他" },
    slug: { current: "others" },
    description: {
      en: "More creative experiences",
      zh: "更多创意体验",
    },
    icon: "sparkles",
    order: 5,
  },
];

export const mockProjects = [
  {
    _id: "mock-project-1",
    name: { en: "Cream Glue Phone Case", zh: "奶油胶手机壳" },
    slug: { current: "cream-glue-phone-case" },
    category: mockCategories[0],
    projectType: "experience",
    description: {
      en: "Design your own unique phone case using cream glue and cute decorations. Perfect for beginners and a great way to express your personal style.",
      zh: "使用奶油胶和可爱装饰设计独一无二的手机壳。适合新手，是表达个人风格的绝佳方式。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-cream/800/600",
    images: [
      "https://picsum.photos/seed/yezz-cream/800/600",
      "https://picsum.photos/seed/yezz-cream2/800/600",
    ],
    priceRange: "¥68 - ¥128",
    duration: "1 - 1.5 hours",
    tags: ["Beginner Friendly", "Cute"],
    order: 1,
  },
  {
    _id: "mock-project-2",
    name: { en: "Paint by Numbers", zh: "数字油画" },
    slug: { current: "paint-by-numbers" },
    category: mockCategories[0],
    projectType: "product",
    description: {
      en: "A relaxing painting experience where you fill in numbered sections.",
      zh: "一种轻松的绘画体验，按照数字填色即可创作出美丽的画作。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-paint/800/600",
    images: [
      "https://picsum.photos/seed/yezz-paint/800/600",
      "https://picsum.photos/seed/yezz-paint2/800/600",
    ],
    priceRange: "¥88 - ¥168",
    duration: "2 - 3 hours",
    tags: ["Relaxing", "Artistic"],
    styles: [
      { name: { en: "Starry Night", zh: "星空主题" }, price: "¥88", imageUrl: "https://picsum.photos/seed/yezz-paint-star/400/400" },
      { name: { en: "Cherry Blossom Street", zh: "樱花街道" }, price: "¥98", imageUrl: "https://picsum.photos/seed/yezz-paint-sakura/400/400" },
      { name: { en: "Cute Pets", zh: "萌宠系列" }, price: "¥68", imageUrl: "https://picsum.photos/seed/yezz-paint-pet/400/400" },
    ],
    order: 2,
  },
  {
    _id: "mock-project-3",
    name: { en: "Beaded Phone Strap", zh: "串珠手机链" },
    slug: { current: "beaded-phone-strap" },
    category: mockCategories[1],
    projectType: "experience",
    description: {
      en: "Create stylish beaded phone straps and keychains. Mix and match colors and charms to make accessories that reflect your taste.",
      zh: "制作时尚的串珠手机链和钥匙扣。混搭颜色和吊坠，打造反映你品味的饰品。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-beads/800/600",
    images: [
      "https://picsum.photos/seed/yezz-beads/800/600",
      "https://picsum.photos/seed/yezz-beads2/800/600",
    ],
    priceRange: "¥48 - ¥98",
    duration: "1 - 1.5 hours",
    tags: ["Fashion", "Portable"],
    order: 3,
  },
  {
    _id: "mock-project-4",
    name: { en: "Handmade Earrings", zh: "手工耳饰" },
    slug: { current: "handmade-earrings" },
    category: mockCategories[1],
    projectType: "experience",
    description: {
      en: "Craft beautiful handmade earrings from various materials. A perfect wearable art piece or gift for someone special.",
      zh: "用各种材料制作精美的手工耳饰。完美的可穿戴艺术品，或是送给特别的人的礼物。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-earring/800/600",
    images: [
      "https://picsum.photos/seed/yezz-earring/800/600",
      "https://picsum.photos/seed/yezz-earring2/800/600",
    ],
    priceRange: "¥58 - ¥128",
    duration: "1 - 2 hours",
    tags: ["Wearable", "Gift"],
    order: 4,
  },
  {
    _id: "mock-project-5",
    name: { en: "Labubu Doll Clothes", zh: "Labubu 娃衣" },
    slug: { current: "labubu-doll-clothes" },
    category: mockCategories[2],
    projectType: "product",
    description: {
      en: "Sew adorable miniature clothes for your Labubu dolls.",
      zh: "为你的 Labubu 玩偶缝制可爱的迷你服装。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-labubu/800/600",
    images: [
      "https://picsum.photos/seed/yezz-labubu/800/600",
      "https://picsum.photos/seed/yezz-labubu2/800/600",
    ],
    priceRange: "¥78 - ¥128",
    duration: "1.5 - 2 hours",
    tags: ["Cute", "Trending"],
    styles: [
      { name: { en: "Pink Dress", zh: "粉色连衣裙" }, price: "¥78", imageUrl: "https://picsum.photos/seed/yezz-labubu-pink/400/400" },
      { name: { en: "Blue Overalls", zh: "蓝色背带裤" }, price: "¥88", imageUrl: "https://picsum.photos/seed/yezz-labubu-blue/400/400" },
      { name: { en: "Holiday Limited Set", zh: "节日限定套装" }, price: "¥128", imageUrl: "https://picsum.photos/seed/yezz-labubu-holiday/400/400" },
    ],
    order: 5,
  },
  {
    _id: "mock-project-6",
    name: { en: "LEGO Building", zh: "LEGO 拼装" },
    slug: { current: "lego-building" },
    category: mockCategories[2],
    projectType: "experience",
    description: {
      en: "Build creative LEGO sets and custom designs. Great for all ages who love to construct and imagine.",
      zh: "拼装创意 LEGO 套装和自定义设计。适合所有热爱搭建和想象的年龄。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-lego/800/600",
    images: [
      "https://picsum.photos/seed/yezz-lego/800/600",
      "https://picsum.photos/seed/yezz-lego2/800/600",
    ],
    priceRange: "¥128 - ¥298",
    duration: "2 - 4 hours",
    tags: ["Building", "Fun"],
    order: 6,
  },
  {
    _id: "mock-project-7",
    name: { en: "Birthday Party DIY", zh: "生日派对 DIY" },
    slug: { current: "birthday-party-diy" },
    category: mockCategories[3],
    projectType: "experience",
    description: {
      en: "Plan and decorate your own birthday party with DIY elements. From handmade invitations to party favors, make it truly yours.",
      zh: "用 DIY 元素策划和装饰你自己的生日派对。从手工邀请函到派对礼物，让它真正成为你的派对。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-bday/800/600",
    images: [
      "https://picsum.photos/seed/yezz-bday/800/600",
      "https://picsum.photos/seed/yezz-bday2/800/600",
    ],
    priceRange: "¥198/person",
    duration: "3 hours",
    tags: ["Party", "Group"],
    order: 7,
  },
  {
    _id: "mock-project-8",
    name: { en: "Photo Booth Party", zh: "拍照机派对" },
    slug: { current: "photo-booth-party" },
    category: mockCategories[3],
    projectType: "experience",
    description: {
      en: "Create fun photo props and backdrops for your own photo booth experience. Capture memories with friends and family.",
      zh: "为你的拍照机体验制作有趣的拍照道具和背景板。与朋友和家人一起捕捉美好回忆。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-photo/800/600",
    images: [
      "https://picsum.photos/seed/yezz-photo/800/600",
      "https://picsum.photos/seed/yezz-photo2/800/600",
    ],
    priceRange: "¥158/person",
    duration: "2 hours",
    tags: ["Photos", "Memories"],
    order: 8,
  },
  {
    _id: "mock-project-9",
    name: { en: "Resin Accessories", zh: "滴胶饰品" },
    slug: { current: "resin-accessories" },
    category: mockCategories[4],
    projectType: "experience",
    description: {
      en: "Make shiny resin accessories like keychains, coasters, and jewelry. Embed flowers, glitter, and charms for unique designs.",
      zh: "制作闪亮的滴胶饰品，如钥匙扣、杯垫和首饰。嵌入花朵、闪粉和吊坠，打造独特设计。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-resin/800/600",
    images: [
      "https://picsum.photos/seed/yezz-resin/800/600",
      "https://picsum.photos/seed/yezz-resin2/800/600",
    ],
    priceRange: "¥68 - ¥138",
    duration: "1.5 - 2 hours",
    tags: ["Shiny", "Unique"],
    order: 9,
  },
  {
    _id: "mock-project-10",
    name: { en: "Squishy Toys", zh: "捏捏乐" },
    slug: { current: "squishy-toys" },
    category: mockCategories[4],
    projectType: "experience",
    description: {
      en: "Create soft and satisfying squishy toys in fun shapes. A stress-relieving craft that's as fun to make as it is to squeeze.",
      zh: "制作各种有趣形状的柔软捏捏乐。一种减压手工，制作过程和捏起来一样有趣。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-squish/800/600",
    images: [
      "https://picsum.photos/seed/yezz-squish/800/600",
      "https://picsum.photos/seed/yezz-squish2/800/600",
    ],
    priceRange: "¥58 - ¥108",
    duration: "1 - 1.5 hours",
    tags: ["Stress Relief", "Fun"],
    order: 10,
  },
];

export const mockParties = [
  {
    _id: "mock-party-1",
    name: { en: "Birthday Celebration", zh: "生日派对套餐" },
    slug: { current: "birthday" },
    description: {
      en: "A memorable birthday experience with friends and family. Choose from a variety of DIY projects and enjoy a private party space decorated just for you.",
      zh: "与亲友共度难忘的生日体验。从多种 DIY 项目中选择，享受专为您装饰的私人派对空间。",
    },
    includes: [
      { en: "Private studio space for 3 hours", zh: "3 小时私人工作室空间" },
      { en: "Birthday decorations", zh: "生日主题装饰" },
      { en: "DIY project for each guest", zh: "每位客人一份 DIY 项目" },
      { en: "Complimentary drinks & snacks", zh: "免费饮品和小食" },
    ],
    imageUrl: "https://picsum.photos/seed/yezz-birthday/800/450",
    images: [
      "https://picsum.photos/seed/yezz-birthday/800/450",
      "https://picsum.photos/seed/yezz-birthday2/800/450",
    ],
    minPeople: 6,
    maxPeople: 15,
    priceIndicator: "From ¥198/person",
    tags: ["Popular", "Customizable"],
  },
  {
    _id: "mock-party-2",
    name: { en: "Couple Date Night", zh: "情侣约会套餐" },
    slug: { current: "couple" },
    description: {
      en: "A romantic evening of creating together. Perfect for anniversaries, first dates, or just quality time with your special someone.",
      zh: "一起创作的浪漫夜晚。适合纪念日、初次约会，或与特别的人共度美好时光。",
    },
    includes: [
      { en: "Couple's DIY project", zh: "情侣 DIY 项目" },
      { en: "Romantic ambient lighting", zh: "浪漫氛围灯光" },
      { en: "Photo opportunity corner", zh: "拍照打卡角" },
      { en: "Take-home gift packaging", zh: "精美带回家包装" },
    ],
    imageUrl: "https://picsum.photos/seed/yezz-couple/800/450",
    images: [
      "https://picsum.photos/seed/yezz-couple/800/450",
      "https://picsum.photos/seed/yezz-couple2/800/450",
    ],
    minPeople: 2,
    maxPeople: 2,
    priceIndicator: "From ¥388/couple",
    tags: ["Romantic", "All-inclusive"],
  },
];

export const mockGalleryImages = [
  {
    _id: "mock-gallery-1",
    imageUrl: "https://picsum.photos/seed/yezz-gal1/800/800",
    category: "couple",
    caption: { en: "Couple creating together", zh: "情侣共同创作" },
    order: 1,
  },
  {
    _id: "mock-gallery-2",
    imageUrl: "https://picsum.photos/seed/yezz-gal2/800/800",
    category: "birthday",
    caption: { en: "Birthday party fun", zh: "生日派对欢乐时光" },
    order: 2,
  },
  {
    _id: "mock-gallery-3",
    imageUrl: "https://picsum.photos/seed/yezz-gal3/800/800",
    category: "kids",
    caption: { en: "Kids exploring creativity", zh: "孩子探索创意" },
    order: 3,
  },
  {
    _id: "mock-gallery-4",
    imageUrl: "https://picsum.photos/seed/yezz-gal4/800/800",
    category: "gift",
    caption: { en: "Handmade gifts", zh: "手工礼物" },
    order: 4,
  },
  {
    _id: "mock-gallery-5",
    imageUrl: "https://picsum.photos/seed/yezz-gal5/800/800",
    category: "store",
    caption: { en: "Our cozy studio", zh: "我们温馨的工作室" },
    order: 5,
  },
  {
    _id: "mock-gallery-6",
    imageUrl: "https://picsum.photos/seed/yezz-gal6/800/800",
    category: "works",
    caption: { en: "Community artworks", zh: "社区作品" },
    order: 6,
  },
];

export const mockStoreImage = {
  _id: "mock-store-1",
  imageUrl: "https://picsum.photos/seed/yezz-store/1200/900",
  caption: { en: "YEZZ Studio Interior", zh: "YEZZ 工作室内部" },
};
