export const mockCategories = [
  {
    _id: "cat-diy",
    name: { en: "DIY / Handmade", zh: "DIY / 手作类" },
    slug: { current: "diy-handmade" },
    description: {
      en: "Create beautiful handmade items with your own hands",
      zh: "用双手创造美好的手工作品",
    },
    icon: "palette",
    order: 1,
  },
  {
    _id: "cat-acc",
    name: { en: "Accessories", zh: "饰品/挂件类" },
    slug: { current: "accessories" },
    description: {
      en: "Stylish accessories and charms you can make yourself",
      zh: "可以自己制作的时尚饰品和挂件",
    },
    icon: "gem",
    order: 2,
  },
  {
    _id: "cat-toys",
    name: { en: "Toys & Blind Box", zh: "玩具/盲盒类" },
    slug: { current: "toys-blindbox" },
    description: {
      en: "Fun toys, blind boxes, and building sets",
      zh: "有趣的玩具、盲盒和拼装模型",
    },
    icon: "box",
    order: 3,
  },
  {
    _id: "cat-events",
    name: { en: "Events & Parties", zh: "活动/派对类" },
    slug: { current: "events-parties" },
    description: {
      en: "Special events and party experiences",
      zh: "特别活动和派对体验",
    },
    icon: "party-popper",
    order: 4,
  },
  {
    _id: "cat-others",
    name: { en: "Others", zh: "其他" },
    slug: { current: "others" },
    description: {
      en: "More creative experiences",
      zh: "更多创意体验",
    },
    icon: "sparkles",
    order: 5,
  },
];

export const mockProjects = [
  // ========== DIY / 手作类 (product + experience) ==========
  {
    _id: "mock-project-1",
    name: { en: "Cream Glue Phone Case", zh: "奶油胶手机壳" },
    slug: { current: "cream-glue-phone-case" },
    category: mockCategories[0],
    projectType: "product",
    description: {
      en: "Design your own unique phone case using cream glue and cute decorations. Choose from dozens of adorable charms, sprinkles, and color combinations to create a case that perfectly matches your style.",
      zh: "使用奶油胶和可爱装饰设计独一无二的手机壳。从数十种可爱的吊坠、闪粉和颜色组合中选择，打造完美匹配你风格的手机壳。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-cream/800/600",
    images: [
      "https://picsum.photos/seed/yezz-cream/800/600",
      "https://picsum.photos/seed/yezz-cream2/800/600",
      "https://picsum.photos/seed/yezz-cream3/800/600",
    ],
    priceRange: "¥68 - ¥128",
    duration: "1 - 1.5 hours",
    tags: ["Beginner Friendly", "Cute", "Popular"],
    styles: [
      { name: { en: "Pastel Pink Bear", zh: "粉色小熊款" }, price: "¥68", imageUrl: "https://picsum.photos/seed/yezz-cream-pink/400/400" },
      { name: { en: "Mint Green Frog", zh: "薄荷青蛙款" }, price: "¥78", imageUrl: "https://picsum.photos/seed/yezz-cream-mint/400/400" },
      { name: { en: "Lavender Dream", zh: "薰衣草梦幻款" }, price: "¥88", imageUrl: "https://picsum.photos/seed/yezz-cream-lavender/400/400" },
      { name: { en: "Classic White Pearl", zh: "经典白珍珠款" }, price: "¥98", imageUrl: "https://picsum.photos/seed/yezz-cream-pearl/400/400" },
      { name: { en: "Rainbow Unicorn", zh: "彩虹独角兽款" }, price: "¥108", imageUrl: "https://picsum.photos/seed/yezz-cream-rainbow/400/400" },
      { name: { en: "Midnight Black Gold", zh: "黑金奢华款" }, price: "¥128", imageUrl: "https://picsum.photos/seed/yezz-cream-black/400/400" },
    ],
    order: 1,
  },
  {
    _id: "mock-project-2",
    name: { en: "Paint by Numbers", zh: "数字油画" },
    slug: { current: "paint-by-numbers" },
    category: mockCategories[0],
    projectType: "product",
    description: {
      en: "A relaxing painting experience where you fill in numbered sections to create a beautiful artwork. No prior painting skills needed. Perfect for unwinding after a long day.",
      zh: "一种轻松的绘画体验，按照数字填色即可创作出美丽的画作。无需任何绘画基础。非常适合在漫长的一天后放松身心。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-paint/800/600",
    images: [
      "https://picsum.photos/seed/yezz-paint/800/600",
      "https://picsum.photos/seed/yezz-paint2/800/600",
      "https://picsum.photos/seed/yezz-paint3/800/600",
    ],
    priceRange: "¥68 - ¥168",
    duration: "2 - 3 hours",
    tags: ["Relaxing", "Artistic", "Beginner Friendly"],
    styles: [
      { name: { en: "Starry Night", zh: "星空主题" }, price: "¥88", imageUrl: "https://picsum.photos/seed/yezz-paint-star/400/400" },
      { name: { en: "Cherry Blossom Street", zh: "樱花街道" }, price: "¥98", imageUrl: "https://picsum.photos/seed/yezz-paint-sakura/400/400" },
      { name: { en: "Cute Pets", zh: "萌宠系列" }, price: "¥68", imageUrl: "https://picsum.photos/seed/yezz-paint-pet/400/400" },
      { name: { en: "Ocean Waves", zh: "海浪风景" }, price: "¥108", imageUrl: "https://picsum.photos/seed/yezz-paint-ocean/400/400" },
      { name: { en: "Sunflower Field", zh: "向日葵花田" }, price: "¥118", imageUrl: "https://picsum.photos/seed/yezz-paint-sunflower/400/400" },
      { name: { en: "Mystical Forest", zh: "神秘森林" }, price: "¥128", imageUrl: "https://picsum.photos/seed/yezz-paint-forest/400/400" },
      { name: { en: "City Nightscape", zh: "城市夜景" }, price: "¥138", imageUrl: "https://picsum.photos/seed/yezz-paint-city/400/400" },
      { name: { en: "Classic Portrait", zh: "经典肖像" }, price: "¥168", imageUrl: "https://picsum.photos/seed/yezz-paint-portrait/400/400" },
    ],
    order: 2,
  },
  {
    _id: "mock-project-3",
    name: { en: "Pottery Experience", zh: "陶艺体验" },
    slug: { current: "pottery-experience" },
    category: mockCategories[0],
    projectType: "experience",
    description: {
      en: "Get your hands dirty and create beautiful ceramic pieces on the pottery wheel. Our instructor will guide you through centering, pulling, and shaping clay into bowls, cups, or vases.",
      zh: "亲手体验拉坯，制作精美的陶瓷作品。我们的导师会指导你完成定心、提拉和塑形，制作出碗、杯子或花瓶。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-pottery/800/600",
    images: [
      "https://picsum.photos/seed/yezz-pottery/800/600",
      "https://picsum.photos/seed/yezz-pottery2/800/600",
      "https://picsum.photos/seed/yezz-pottery3/800/600",
    ],
    priceRange: "¥158 - ¥228",
    duration: "2 - 2.5 hours",
    tags: ["Hands-on", "Relaxing", "Unique"],
    order: 3,
  },
  {
    _id: "mock-project-4",
    name: { en: "Scented Candle Making", zh: "香薰蜡烛制作" },
    slug: { current: "scented-candle" },
    category: mockCategories[0],
    projectType: "experience",
    description: {
      en: "Create your own signature scented candles. Choose from premium fragrance oils, natural soy wax, and elegant containers. Perfect for setting the mood in your home or as a thoughtful gift.",
      zh: "制作属于你标志性的香薰蜡烛。从优质香精油、天然大豆蜡和优雅容器中自由选择。非常适合营造家居氛围或作为贴心礼物。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-candle/800/600",
    images: [
      "https://picsum.photos/seed/yezz-candle/800/600",
      "https://picsum.photos/seed/yezz-candle2/800/600",
    ],
    priceRange: "¥98 - ¥168",
    duration: "1.5 - 2 hours",
    tags: ["Aromatic", "Gift-worthy", "Romantic"],
    order: 4,
  },

  // ========== 饰品/挂件类 (product) ==========
  {
    _id: "mock-project-5",
    name: { en: "Handmade Earrings", zh: "手工耳饰" },
    slug: { current: "handmade-earrings" },
    category: mockCategories[1],
    projectType: "product",
    description: {
      en: "Craft beautiful handmade earrings from various materials including freshwater pearls, crystals, polymer clay, and gold-plated findings. Design pieces that reflect your personal aesthetic.",
      zh: "用淡水珍珠、水晶、软陶和镀金配件等各种材料制作精美的手工耳饰。设计出反映你个人审美的作品。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-earring/800/600",
    images: [
      "https://picsum.photos/seed/yezz-earring/800/600",
      "https://picsum.photos/seed/yezz-earring2/800/600",
      "https://picsum.photos/seed/yezz-earring3/800/600",
    ],
    priceRange: "¥58 - ¥168",
    duration: "1 - 2 hours",
    tags: ["Wearable", "Gift", "Elegant"],
    styles: [
      { name: { en: "Pearl Drop", zh: "珍珠垂坠款" }, price: "¥58", imageUrl: "https://picsum.photos/seed/yezz-earring-pearl/400/400" },
      { name: { en: "Crystal Stud", zh: "水晶耳钉款" }, price: "¥68", imageUrl: "https://picsum.photos/seed/yezz-earring-crystal/400/400" },
      { name: { en: "Floral Clay", zh: "花卉软陶款" }, price: "¥78", imageUrl: "https://picsum.photos/seed/yezz-earring-clay/400/400" },
      { name: { en: "Gold Hoop", zh: "镀金圆环款" }, price: "¥88", imageUrl: "https://picsum.photos/seed/yezz-earring-hoop/400/400" },
      { name: { en: "Vintage Tassel", zh: "复古流苏款" }, price: "¥108", imageUrl: "https://picsum.photos/seed/yezz-earring-tassel/400/400" },
      { name: { en: "Diamond Cluster", zh: "钻石簇聚款" }, price: "¥168", imageUrl: "https://picsum.photos/seed/yezz-earring-diamond/400/400" },
    ],
    order: 5,
  },
  {
    _id: "mock-project-6",
    name: { en: "Beaded Phone Strap", zh: "串珠手机链" },
    slug: { current: "beaded-phone-strap" },
    category: mockCategories[1],
    projectType: "product",
    description: {
      en: "Create stylish beaded phone straps and keychains. Mix and match colors, shapes, and charms to make accessories that reflect your taste. Over 50 bead types to choose from.",
      zh: "制作时尚的串珠手机链和钥匙扣。混搭颜色、形状和吊坠，打造反映你品味的饰品。超过50种珠子可供选择。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-beads/800/600",
    images: [
      "https://picsum.photos/seed/yezz-beads/800/600",
      "https://picsum.photos/seed/yezz-beads2/800/600",
      "https://picsum.photos/seed/yezz-beads3/800/600",
    ],
    priceRange: "¥48 - ¥128",
    duration: "1 - 1.5 hours",
    tags: ["Fashion", "Portable", "Trending"],
    styles: [
      { name: { en: "Y2K Colorful", zh: "Y2K彩色款" }, price: "¥48", imageUrl: "https://picsum.photos/seed/yezz-beads-y2k/400/400" },
      { name: { en: "Minimalist Pearl", zh: "极简珍珠款" }, price: "¥68", imageUrl: "https://picsum.photos/seed/yezz-beads-pearl/400/400" },
      { name: { en: "Cute Charms", zh: "可爱吊坠款" }, price: "¥78", imageUrl: "https://picsum.photos/seed/yezz-beads-charms/400/400" },
      { name: { en: "Crystal Rainbow", zh: "水晶彩虹款" }, price: "¥98", imageUrl: "https://picsum.photos/seed/yezz-beads-rainbow/400/400" },
      { name: { en: "Luxury Gold", zh: "奢华金色款" }, price: "¥128", imageUrl: "https://picsum.photos/seed/yezz-beads-gold/400/400" },
    ],
    order: 6,
  },

  // ========== 玩具/盲盒类 (product) ==========
  {
    _id: "mock-project-7",
    name: { en: "Labubu Doll Clothes", zh: "Labubu 娃衣" },
    slug: { current: "labubu-doll-clothes" },
    category: mockCategories[2],
    projectType: "product",
    description: {
      en: "Sew adorable miniature clothes for your Labubu dolls. A trending craft that combines fashion design with doll collecting. Each outfit is meticulously designed with tiny buttons, lace, and embroidery details.",
      zh: "为你的 Labubu 玩偶缝制可爱的迷你服装。一种结合时装设计与玩偶收藏的热门手工。每件服装都精心设计，带有微型纽扣、蕾丝和刺绣细节。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-labubu/800/600",
    images: [
      "https://picsum.photos/seed/yezz-labubu/800/600",
      "https://picsum.photos/seed/yezz-labubu2/800/600",
      "https://picsum.photos/seed/yezz-labubu3/800/600",
    ],
    priceRange: "¥78 - ¥188",
    duration: "1.5 - 2 hours",
    tags: ["Cute", "Trending", "Popular"],
    styles: [
      { name: { en: "Pink Dress", zh: "粉色连衣裙" }, price: "¥78", imageUrl: "https://picsum.photos/seed/yezz-labubu-pink/400/400" },
      { name: { en: "Blue Overalls", zh: "蓝色背带裤" }, price: "¥88", imageUrl: "https://picsum.photos/seed/yezz-labubu-blue/400/400" },
      { name: { en: "Holiday Limited Set", zh: "节日限定套装" }, price: "¥128", imageUrl: "https://picsum.photos/seed/yezz-labubu-holiday/400/400" },
      { name: { en: "Wedding Gown", zh: "婚纱礼服款" }, price: "¥148", imageUrl: "https://picsum.photos/seed/yezz-labubu-wedding/400/400" },
      { name: { en: "Hanfu Traditional", zh: "汉服传统款" }, price: "¥158", imageUrl: "https://picsum.photos/seed/yezz-labubu-hanfu/400/400" },
      { name: { en: "Designer Collection", zh: "设计师联名款" }, price: "¥188", imageUrl: "https://picsum.photos/seed/yezz-labubu-designer/400/400" },
    ],
    order: 7,
  },
  {
    _id: "mock-project-8",
    name: { en: "LEGO Building", zh: "LEGO 拼装" },
    slug: { current: "lego-building" },
    category: mockCategories[2],
    projectType: "experience",
    description: {
      en: "Build creative LEGO sets and custom designs. Great for all ages who love to construct and imagine. Choose from architectural landmarks, vehicles, or free-form creative builds.",
      zh: "拼装创意 LEGO 套装和自定义设计。适合所有热爱搭建和想象的年龄。可选择建筑地标、交通工具或自由创意搭建。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-lego/800/600",
    images: [
      "https://picsum.photos/seed/yezz-lego/800/600",
      "https://picsum.photos/seed/yezz-lego2/800/600",
    ],
    priceRange: "¥128 - ¥298",
    duration: "2 - 4 hours",
    tags: ["Building", "Fun", "All Ages"],
    order: 8,
  },
  {
    _id: "mock-project-9",
    name: { en: "Blind Box Customizing", zh: "盲盒改娃" },
    slug: { current: "blind-box-custom" },
    category: mockCategories[2],
    projectType: "product",
    description: {
      en: "Transform ordinary blind box figures into one-of-a-kind art pieces. Use airbrushing, repainting, and accessory crafting to give your favorite characters a brand new look.",
      zh: "将普通盲盒人偶改造成独一无二的艺术品。使用喷绘、重涂和配件制作，为你喜爱的角色打造全新造型。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-blindbox/800/600",
    images: [
      "https://picsum.photos/seed/yezz-blindbox/800/600",
      "https://picsum.photos/seed/yezz-blindbox2/800/600",
      "https://picsum.photos/seed/yezz-blindbox3/800/600",
    ],
    priceRange: "¥88 - ¥198",
    duration: "2 - 3 hours",
    tags: ["Artistic", "Unique", "Trending"],
    styles: [
      { name: { en: "Fantasy Fairy", zh: "梦幻仙子款" }, price: "¥88", imageUrl: "https://picsum.photos/seed/yezz-blindbox-fairy/400/400" },
      { name: { en: "Cyberpunk Style", zh: "赛博朋克款" }, price: "¥118", imageUrl: "https://picsum.photos/seed/yezz-blindbox-cyber/400/400" },
      { name: { en: "Royal Princess", zh: "皇室公主款" }, price: "¥138", imageUrl: "https://picsum.photos/seed/yezz-blindbox-princess/400/400" },
      { name: { en: "Space Explorer", zh: "太空探险款" }, price: "¥158", imageUrl: "https://picsum.photos/seed/yezz-blindbox-space/400/400" },
      { name: { en: "Limited Edition", zh: "限量版" }, price: "¥198", imageUrl: "https://picsum.photos/seed/yezz-blindbox-limited/400/400" },
    ],
    order: 9,
  },

  // ========== 活动/派对类 (experience) ==========
  {
    _id: "mock-project-10",
    name: { en: "Birthday Party DIY", zh: "生日派对 DIY" },
    slug: { current: "birthday-party-diy" },
    category: mockCategories[3],
    projectType: "experience",
    description: {
      en: "Plan and decorate your own birthday party with DIY elements. From handmade invitations to party favors, cake toppers, and themed decorations — make it truly yours. Perfect for kids and adults alike.",
      zh: "用 DIY 元素策划和装饰你自己的生日派对。从手工邀请函到派对礼物、蛋糕装饰和主题装饰，让它真正成为你的派对。适合儿童和成人。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-bday/800/600",
    images: [
      "https://picsum.photos/seed/yezz-bday/800/600",
      "https://picsum.photos/seed/yezz-bday2/800/600",
      "https://picsum.photos/seed/yezz-bday3/800/600",
    ],
    priceRange: "¥198/person",
    duration: "3 hours",
    tags: ["Party", "Group", "Celebration"],
    order: 10,
  },
  {
    _id: "mock-project-11",
    name: { en: "Couple Date Night", zh: "情侣约会之夜" },
    slug: { current: "couple-date-night" },
    category: mockCategories[3],
    projectType: "experience",
    description: {
      en: "A romantic evening of creating together. Work on complementary projects like matching keychains, couple mugs, or a shared painting. Includes candlelit ambiance and complimentary sparkling wine.",
      zh: "一起创作的浪漫夜晚。制作配套项目，如配对钥匙扣、情侣马克杯或共同完成的画作。包括烛光氛围和免费起泡酒。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-couple/800/600",
    images: [
      "https://picsum.photos/seed/yezz-couple/800/600",
      "https://picsum.photos/seed/yezz-couple2/800/600",
    ],
    priceRange: "¥388/couple",
    duration: "2.5 hours",
    tags: ["Romantic", "Date", "Special"],
    order: 11,
  },
  {
    _id: "mock-project-12",
    name: { en: "Kids Creative Workshop", zh: "儿童创意工作坊" },
    slug: { current: "kids-workshop" },
    category: mockCategories[3],
    projectType: "experience",
    description: {
      en: "A fun-filled workshop designed for children aged 6-12. Kids explore various crafts under gentle guidance, creating their own masterpieces to take home. Parents can join in or relax in our lounge.",
      zh: "专为6-12岁儿童设计的趣味工作坊。孩子们在温和指导下探索各种手工艺，创作属于自己的杰作带回家。家长可以参与或在我们的休息室放松。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-kids/800/600",
    images: [
      "https://picsum.photos/seed/yezz-kids/800/600",
      "https://picsum.photos/seed/yezz-kids2/800/600",
    ],
    priceRange: "¥128/child",
    duration: "2 hours",
    tags: ["Kids", "Educational", "Fun"],
    order: 12,
  },

  // ========== 其他 (product + experience) ==========
  {
    _id: "mock-project-13",
    name: { en: "Resin Accessories", zh: "滴胶饰品" },
    slug: { current: "resin-accessories" },
    category: mockCategories[4],
    projectType: "product",
    description: {
      en: "Make shiny resin accessories like keychains, coasters, and jewelry. Embed flowers, glitter, and charms for unique designs. Each piece is a tiny universe captured in crystal-clear resin.",
      zh: "制作闪亮的滴胶饰品，如钥匙扣、杯垫和首饰。嵌入花朵、闪粉和吊坠，打造独特设计。每件作品都是捕捉在晶莹剔透树脂中的微型宇宙。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-resin/800/600",
    images: [
      "https://picsum.photos/seed/yezz-resin/800/600",
      "https://picsum.photos/seed/yezz-resin2/800/600",
      "https://picsum.photos/seed/yezz-resin3/800/600",
    ],
    priceRange: "¥68 - ¥158",
    duration: "1.5 - 2 hours",
    tags: ["Shiny", "Unique", "Gift-worthy"],
    styles: [
      { name: { en: "Dried Flower Keychain", zh: "干花钥匙扣" }, price: "¥68", imageUrl: "https://picsum.photos/seed/yezz-resin-flower/400/400" },
      { name: { en: "Glitter Coaster Set", zh: "闪粉杯垫套装" }, price: "¥88", imageUrl: "https://picsum.photos/seed/yezz-resin-coaster/400/400" },
      { name: { en: "Ocean Wave Pendant", zh: "海浪吊坠" }, price: "¥98", imageUrl: "https://picsum.photos/seed/yezz-resin-ocean/400/400" },
      { name: { en: "Galaxy Jewelry Set", zh: "银河首饰套装" }, price: "¥128", imageUrl: "https://picsum.photos/seed/yezz-resin-galaxy/400/400" },
      { name: { en: "Custom Photo Frame", zh: "定制相框" }, price: "¥158", imageUrl: "https://picsum.photos/seed/yezz-resin-frame/400/400" },
    ],
    order: 13,
  },
  {
    _id: "mock-project-14",
    name: { en: "Leather Craft Workshop", zh: "皮革手作工坊" },
    slug: { current: "leather-craft" },
    category: mockCategories[4],
    projectType: "experience",
    description: {
      en: "Learn the art of leather crafting. Create wallets, card holders, or keychains from genuine leather. Hand-stitch with waxed thread and personalize with embossed initials.",
      zh: "学习皮革手工艺。用真皮制作钱包、卡包或钥匙扣。用蜡线手工缝制，并用压印首字母进行个性化定制。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-leather/800/600",
    images: [
      "https://picsum.photos/seed/yezz-leather/800/600",
      "https://picsum.photos/seed/yezz-leather2/800/600",
    ],
    priceRange: "¥138 - ¥258",
    duration: "2 - 3 hours",
    tags: ["Premium", "Durable", "Classic"],
    order: 14,
  },
  {
    _id: "mock-project-15",
    name: { en: "Floral Arrangement", zh: "花艺设计" },
    slug: { current: "floral-arrangement" },
    category: mockCategories[4],
    projectType: "experience",
    description: {
      en: "Design stunning floral arrangements with fresh seasonal flowers. Learn color theory, composition techniques, and care tips. Take home a beautiful bouquet or centerpiece.",
      zh: "用新鲜时令花卉设计令人惊叹的花艺作品。学习色彩理论、构图技巧和养护知识。带一束美丽的花束或桌花回家。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-flower/800/600",
    images: [
      "https://picsum.photos/seed/yezz-flower/800/600",
      "https://picsum.photos/seed/yezz-flower2/800/600",
      "https://picsum.photos/seed/yezz-flower3/800/600",
    ],
    priceRange: "¥168 - ¥298",
    duration: "1.5 - 2 hours",
    tags: ["Elegant", "Seasonal", "Relaxing"],
    order: 15,
  },
  {
    _id: "mock-project-16",
    name: { en: "Squishy Toys", zh: "捏捏乐" },
    slug: { current: "squishy-toys" },
    category: mockCategories[4],
    projectType: "product",
    description: {
      en: "Create soft and satisfying squishy toys in fun shapes. A stress-relieving craft that's as fun to make as it is to squeeze. Choose from food shapes, animals, or custom designs.",
      zh: "制作各种有趣形状的柔软捏捏乐。一种减压手工，制作过程和捏起来一样有趣。可选择食物造型、动物或自定义设计。",
    },
    imageUrl: "https://picsum.photos/seed/yezz-squish/800/600",
    images: [
      "https://picsum.photos/seed/yezz-squish/800/600",
      "https://picsum.photos/seed/yezz-squish2/800/600",
      "https://picsum.photos/seed/yezz-squish3/800/600",
    ],
    priceRange: "¥58 - ¥138",
    duration: "1 - 1.5 hours",
    tags: ["Stress Relief", "Fun", "Cute"],
    styles: [
      { name: { en: "Mini Toast", zh: "迷你吐司款" }, price: "¥58", imageUrl: "https://picsum.photos/seed/yezz-squish-toast/400/400" },
      { name: { en: "Paw Pillow", zh: "猫爪抱枕款" }, price: "¥68", imageUrl: "https://picsum.photos/seed/yezz-squish-paw/400/400" },
      { name: { en: "Bunny Ear", zh: "兔耳朵款" }, price: "¥78", imageUrl: "https://picsum.photos/seed/yezz-squish-bunny/400/400" },
      { name: { en: "Giant Panda", zh: "大熊猫款" }, price: "¥98", imageUrl: "https://picsum.photos/seed/yezz-squish-panda/400/400" },
      { name: { en: "Custom Shape", zh: "自定义造型" }, price: "¥138", imageUrl: "https://picsum.photos/seed/yezz-squish-custom/400/400" },
    ],
    order: 16,
  },
];

export const mockParties = [
  {
    _id: "mock-party-1",
    name: { en: "Birthday Celebration", zh: "生日派对套餐" },
    slug: { current: "birthday" },
    description: {
      en: "A memorable birthday experience with friends and family. Choose from a variety of DIY projects and enjoy a private party space decorated just for you.",
      zh: "与亲友共度难忘的生日体验。从多种 DIY 项目中选择，享受专为您装饰的私人派对空间。",
    },
    includes: [
      { en: "Private studio space for 3 hours", zh: "3 小时私人工作室空间" },
      { en: "Birthday decorations", zh: "生日主题装饰" },
      { en: "DIY project for each guest", zh: "每位客人一份 DIY 项目" },
      { en: "Complimentary drinks & snacks", zh: "免费饮品和小食" },
    ],
    imageUrl: "https://picsum.photos/seed/yezz-birthday/800/450",
    images: [
      "https://picsum.photos/seed/yezz-birthday/800/450",
      "https://picsum.photos/seed/yezz-birthday2/800/450",
    ],
    minPeople: 6,
    maxPeople: 15,
    priceIndicator: "From ¥198/person",
    tags: ["Popular", "Customizable"],
  },
  {
    _id: "mock-party-2",
    name: { en: "Couple Date Night", zh: "情侣约会套餐" },
    slug: { current: "couple" },
    description: {
      en: "A romantic evening of creating together. Perfect for anniversaries, first dates, or just quality time with your special someone.",
      zh: "一起创作的浪漫夜晚。适合纪念日、初次约会，或与特别的人共度美好时光。",
    },
    includes: [
      { en: "Couple's DIY project", zh: "情侣 DIY 项目" },
      { en: "Romantic ambient lighting", zh: "浪漫氛围灯光" },
      { en: "Photo opportunity corner", zh: "拍照打卡角" },
      { en: "Take-home gift packaging", zh: "精美带回家包装" },
    ],
    imageUrl: "https://picsum.photos/seed/yezz-couple/800/450",
    images: [
      "https://picsum.photos/seed/yezz-couple/800/450",
      "https://picsum.photos/seed/yezz-couple2/800/450",
    ],
    minPeople: 2,
    maxPeople: 2,
    priceIndicator: "From ¥388/couple",
    tags: ["Romantic", "All-inclusive"],
  },
  {
    _id: "mock-party-3",
    name: { en: "Corporate Team Building", zh: "企业团建套餐" },
    slug: { current: "corporate" },
    description: {
      en: "Boost team morale with a creative workshop. Customizable projects, catering options, and professional photography available. Perfect for company outings and team bonding.",
      zh: "通过创意工作坊提升团队士气。可定制项目、餐饮选择和专业摄影服务。非常适合公司外出活动和团队建设。",
    },
    includes: [
      { en: "Private studio for 4 hours", zh: "4 小时私人工作室" },
      { en: "Team-building games", zh: "团队建设游戏" },
      { en: "Group project or individual crafts", zh: "团体项目或个人手工" },
      { en: "Professional event photography", zh: "专业活动摄影" },
      { en: "Catering service available", zh: "可提供餐饮服务" },
    ],
    imageUrl: "https://picsum.photos/seed/yezz-corporate/800/450",
    images: [
      "https://picsum.photos/seed/yezz-corporate/800/450",
      "https://picsum.photos/seed/yezz-corporate2/800/450",
    ],
    minPeople: 10,
    maxPeople: 40,
    priceIndicator: "From ¥168/person",
    tags: ["Team Building", "Corporate"],
  },
];

export const mockGalleryImages = [
  {
    _id: "mock-gallery-1",
    imageUrl: "https://picsum.photos/seed/yezz-gal1/800/800",
    category: "couple",
    caption: { en: "Couple creating together", zh: "情侣共同创作" },
    order: 1,
  },
  {
    _id: "mock-gallery-2",
    imageUrl: "https://picsum.photos/seed/yezz-gal2/800/800",
    category: "birthday",
    caption: { en: "Birthday party fun", zh: "生日派对欢乐时光" },
    order: 2,
  },
  {
    _id: "mock-gallery-3",
    imageUrl: "https://picsum.photos/seed/yezz-gal3/800/800",
    category: "kids",
    caption: { en: "Kids exploring creativity", zh: "孩子探索创意" },
    order: 3,
  },
  {
    _id: "mock-gallery-4",
    imageUrl: "https://picsum.photos/seed/yezz-gal4/800/800",
    category: "gift",
    caption: { en: "Handmade gifts", zh: "手工礼物" },
    order: 4,
  },
  {
    _id: "mock-gallery-5",
    imageUrl: "https://picsum.photos/seed/yezz-gal5/800/800",
    category: "store",
    caption: { en: "Our cozy studio", zh: "我们温馨的工作室" },
    order: 5,
  },
  {
    _id: "mock-gallery-6",
    imageUrl: "https://picsum.photos/seed/yezz-gal6/800/800",
    category: "works",
    caption: { en: "Community artworks", zh: "社区作品" },
    order: 6,
  },
  {
    _id: "mock-gallery-7",
    imageUrl: "https://picsum.photos/seed/yezz-gal7/800/800",
    category: "works",
    caption: { en: "Beautiful resin coasters", zh: "精美滴胶杯垫" },
    order: 7,
  },
  {
    _id: "mock-gallery-8",
    imageUrl: "https://picsum.photos/seed/yezz-gal8/800/800",
    category: "couple",
    caption: { en: "Matching couple keychains", zh: "情侣配对钥匙扣" },
    order: 8,
  },
  {
    _id: "mock-gallery-9",
    imageUrl: "https://picsum.photos/seed/yezz-gal9/800/800",
    category: "birthday",
    caption: { en: "Birthday cake decoration", zh: "生日蛋糕装饰" },
    order: 9,
  },
];

export const mockStoreImage = {
  _id: "mock-store-1",
  imageUrl: "https://picsum.photos/seed/yezz-store/1200/900",
  caption: { en: "YEZZ Studio Interior", zh: "YEZZ 工作室内部" },
};
